### ISSUE TITLE
how can I install or use it in Linux

### ISSUE THREAD

**Issue by huangrh99** [P3TE/Autonomous-Surface-Vehicle-Simulator#1]
I don't know how to install this simulator.

**Comment by P3TE** [comment]
Hi Ezra-H,

I actually made a video tutorial on how to do this, I made the video in Windows, but the same steps should work in linux.
You can find the video tutorial here: https://www.youtube.com/watch?v=weAIRonzOd0&feature=youtu.be
or you can check out the post about this on the wiki:
https://github.com/P3TE/Autonomous-Surface-Vehicle-Simulator/wiki

If you have any troubles, let me know and I'll help you out.

**Comment by huangrh99** [comment]
Thanks for responding to my problem so fast. I followed it in Windows to find if it works. But I found "can not find the symbol in class Mutex"
![image](https://user-images.githubusercontent.com/44772185/58819893-c9fa0200-8663-11e9-8f87-2d9082e7f017.png)

**Comment by P3TE** [comment]
Hey, I think I've identified the problem as the fact that Mutex has been changed to Lock in newer versions of Java. I've changed that code so try pulling the latest version of master and see if that fixes your problem.

**Comment by huangrh99** [comment]
Thanks! The "Mutex" error is solved. But come out another error: cannot solve symbol "vecmath" ". It says "the javax.vecmath doesn't exist". I first use and not familiar with Intellij and java.

**Comment by P3TE** [comment]
The vecmath error would probably be caused by a missing dependency. I would recommend going through the video tutorial again and making sure that all the dependencies are setup correctly. If you still have any troubles after that let me know.

**Comment by huangrh99** [comment]
Thanks a lot!! I compared with the video and found the global dependency has to be added to Modules. After that, it works. And it also runs in Linux only if change the dependency “windows” to “Linux”.
