### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by dimosthenis8** [P3TE/Autonomous-Surface-Vehicle-Simulator#5]
Hi,
Im trying to use the simulator, i follow the instructions, but when i build it, it gives me the error:
java: package com.sun.istack.internal does not exist
Any idea what should i change?
Thank you in advance

**Comment by dimosthenis8** [comment]
i was the java version. Now it works

**Comment by P3TE** [comment]
Hey, glad you got it working. Out of curiosity, which Java version didn't work and which one did you upgrade to? I can add it to the project description so others won't have the same problem.
If you have any other questions, feel free to ask.

**Comment by dimosthenis8** [comment]
To make it run i used Java 1.8.0_262. 
Im trying to get familiar with the simulator and I cant find where are the sensors scan results shown or stored.

**Comment by P3TE** [comment]
Thanks for posting your Java version.

As for where the sensor results are shown/stored. The main sensor data is shown on screen. There is actually another piece of software that interfaces with this simulator that publishes the sensor data to ROS which is quite a lot more useful for developing AI systems. However unfortunately that software isn't owned solely by me so I can't publish it publicly without permission. My suggestion would be to use the methods and techniques developed here and apply them to other simulators such as Gazebo. The method for LiDAR simulation in this codebase is a very efficient way of simulating large point clouds and would be one of the main take aways from this project.
